name: Publish VS Code Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x' # Use the Node.js version compatible with Vite

    - name: Install root dependencies
      run: npm install

    - name: Install webview-ui dependencies
      run: cd webview-ui && npm install

    - name: Compile extension
      run: npm run compile

    - name: Run tests
      run: npm test
      continue-on-error: true # Allow publishing even if tests fail, but ideally tests should pass

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install vsce
      run: npm install -g vsce

    - name: Install root dependencies (for publish job)
      run: npm install

    - name: Install webview-ui dependencies (for publish job)
      run: cd webview-ui && npm install

    - name: Publish extension
      run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
